---
title: "Working Code Base for Capstone"
author: "Pratyush Pati"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r sample, include=FALSE}
############# Notes/Sample Code Plot testing ###################

# ############### Pre-EDA with multiple_platform dataset#################
# # Frequency Counts of games released on multiple platform
# multiple_platform_counts <- data.frame(table(multiple_platform$title))
# multiple_platform_counts$Won = ""
# 
# multiple_platform_counts$Won <- multiple_platform[match(multiple_platform_counts$Var1, multiple_platform$title),8]
# 
# # New column is correctly mode as a character column
# multiple_platform_counts$Won <- unlist(multiple_platform_counts$Won)
# 
# # Plotting Number of Editors Choice Award won vs. Number of Platforms Released On
# ggplot(multiple_platform_counts, aes(x = factor(Freq), fill = factor(Won))) +
#   geom_bar() +
#   xlab("Number of Platforms Released") +
#   ylab("Number of Editor's Choice Awards") +
#   labs(title = "Editors Choice Award won vs. Number of Platforms Released On") 

#For each genre/platform figure way to get mean
#a <- aggregate(ign$score~ign$platform, FUN = mean OR median)  # for creating mean a dataframe
# hist(ign$score)
# 
# barplot(a$`ign$score`,names.arg=a$`ign$platform`)
# barplot(a[,2],a[,1])
# barplot(a[,2],names.arg=a[,1])
# 
# n_occur <- data.frame(table(vocabulary$id))
# 
# data.frame ( table ( data$Group, data$Size ) )

#multiple_platform_counts[] <- lapply(multiple_platform_counts, as.character)

# for(r in 1:nrow(multiple_platform_counts)){
#   if(multiple_platform_counts[r,3] == 'N'){
#     multiple_platform_counts[r,3] = 0
#   } else{
#     multiple_platform_counts[r,3] = 1
#   }
# }

# multiple_platform_counts$Won <- data.matrix(multiple_platform_counts)

# # Assign 1 for Yes or 0 for No if game appears on that platform
# for (i in 1:nrow(ign_revised)) {
#   for (j in 12:ncol(ign_revised)) {
#     temp_title = ign_revised[i,3]
#     temp_platform = ign_revised[i,j]
#     if((temp_title %in% ign_temp$title)&(temp_platform %in% ign_temp$platform)) {
#       ign_revised[i,j] <- 1
#     } else{
#       ign_revised[i,j] <- 0
#     }
#   }
# }

        ## + scale_x_discrete(expand = c(0,0.6))                   #Spacing 
# df_test <- ign_revised %>% select(title, editors_choice, Android:`Xbox One`)
# df_test <- melt(df_test, id.vars = dis_platform, measure.vars = "editors_choice")
#  
# # ggplot(df_test, aes(x=dis_platform, y=value, fill=variable)) + geom_bar(stat='identity')

# df_sums <- ign_revised %>% select(Android:`Xbox One`) %>% 
#   mutate(tot_platforms = rowSums(.[1:24]))

#########OLD EDA Plots######################################

# # Plotting Mean Scores of Genre
# meanScore_Plat <- aggregate(ign_revised$score~ign_revised$genre, FUN = mean)
# colnames(meanScore_Plat) <- c("Genre", "Mean_Score")
# ggplot(meanScore_Plat, aes(x = Genre, y = Mean_Score)) + 
#   geom_point(col = "Blue") +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1),
#         axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 10)) +
#         labs(title = "Mean Score of Games of All Genre from 2012-2016", 
#              x = "Genre", 
#              y = "Mean Score")

# # Plotting Mean Score of Year
# meanScore_year <- aggregate(ign_revised$score~ign_revised$release_year, FUN = mean)
# colnames(meanScore_year) <- c("Year", "Mean_Score")
# ggplot(meanScore_year, aes(x = Year, y = Mean_Score)) + 
#   geom_point(col = "Blue") +
#   theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 10)) +
#         labs(title = "Mean Score of Games from 2012-2016", 
#              x = "Year", 
#              y = "Mean Score")

# # Plotting Count of Editor's Choice award won per Genre
# ggplot(ign_revised, aes(x = genre, ..count..)) + 
#   geom_bar(aes(fill = factor(editors_choice)), position = "stack") +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1),
#         axis.title.y = element_text(angle = 0, vjust = 0.5),
#         axis.ticks.margin=unit(c(4,-4),'cm'),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 300)) +
#         labs(title = "Number of Editor's Choice Award by Genre in 2012-2016", 
#              x = "Genre", 
#              y = "# of Video Games") +
#         scale_fill_manual(values = c("#ff6666", "blue"),
#                         name="Editor's Choice\nAward",
#                          breaks=c("N", "Y"),
#                          labels=c("No", "Yes")) 

# # Plotting Proportion of Editor's Choice award won per Genre
# ggplot(ign_revised, aes(x = genre, fill = factor(editors_choice))) + 
#   geom_bar(position = "fill") +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1),
#         axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
#         labs(title = "Proportion of Editor's Choice Award by Genre in 2012-2016", 
#              x = "Genre", 
#              y = "Proportion of Video Games") +
#         scale_fill_manual(values = c("#ff6666", "blue"),
#                         name="Editor's Choice\nAward",
#                          breaks=c("N", "Y"),
#                          labels=c("No", "Yes"))

# # Plotting Count of Editor's Choice award won per Year
# ggplot(ign_revised, aes(x = release_year, fill = factor(editors_choice))) +
#   geom_histogram(binwidth = 0.5, position = "dodge") +
#   theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
#         axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 400)) +
#         labs(title = "Number of Editor's Choice Award by Year in 2012-2016", 
#              x = "Year", 
#              y = "# of Video Games") +
#         scale_fill_manual(values = c("#ff6666", "blue"),
#                         name="Editor's Choice\nAward",
#                          breaks=c("N", "Y"),
#                          labels=c("No", "Yes"))

# # Plotting Proportion of Editor's Choice award won per Year
# ggplot(ign_revised, aes(x = release_year, fill = factor(editors_choice))) +
#   geom_bar(position = "fill", col = "black") +
#   theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
#         labs(title = "Proportion of Editor's Choice Award in 2012-2016", 
#              x = "Year", 
#              y = "Proportion of Video Games") +
#         scale_fill_manual(values = c("#ff6666", "blue"),
#                         name="Editor's Choice\nAward",
#                          breaks=c("N", "Y"),
#                          labels=c("No", "Yes"))

# # Plotting Count of Editor's Choice award won per Platform
# ggplot(tot_platform, aes(x = Platform, y = Games, fill = award)) + 
#   geom_bar(position = "stack", stat = "identity") +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1),
#         axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 725)) +
#         labs(title = "Number of Editor's Choice Award by Platform in 2012-2016",
#              x = "Platform",
#              y = "# of Video Games") +
#         scale_fill_manual(values = c("#ff6666", "blue"),
#                         name="Editor's Choice\nAward",
#                          breaks=c("Lost", "Won"),
#                          labels=c("No", "Yes"))

# # Plotting Proportion of Editor's Choice award won per Platform 
# ggplot(tot_plat2_tidy, aes(x = Platform, y = prop, fill = variable)) + 
#   geom_bar(stat = 'identity') +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1),
#         axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
#         labs(title = "Proportion of Editor's Choice Award by Genre in 2012-2016", 
#              x = "Platform", 
#              y = "Proportion of Video Games") +
#         scale_fill_manual(values = c("#ff6666", "blue"),
#                         name="Editor's Choice\nAward",
#                          breaks=c("Lost", "Won"),
#                          labels=c("No", "Yes"))

#  
# ggplot(tot_platform, aes(factor(award), Games)) +
#   geom_boxplot() +
#   theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
#         plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
#         scale_y_continuous(expand = c(0, 0), limits = c(0, 725)) +
#         labs(title = "Number of Platforms of Winners of Editor's Choice in 2012-2016",
#              x = "Editor's Choice Award",
#              y = "Total Sum of Video Games") 

#############################################################################
```

```{r package_options, include=FALSE}
install.packages("plyr")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("data.table")
install.packages("caTools")
install.packages("ROCR")

library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(caTools)
library(ROCR)

####### Helper Function For Standard Error/CI from R Cookbook ####################
st.err <- function(x) {
    sd(x)/sqrt(length(x))
     }

```

```{r ign, include=FALSE}
#################### EDA: Data Wrangling ##########################

# Obtain original ign dataset
ign <- read.csv("ign.csv", header=TRUE)

# Creation of the wrangled dataset
ign_order <- ign[order(ign$title),]
ign_revised <- ign

# Change class to appropriate types
ign_revised$title <- as.character(ign_revised$title)
ign_revised$genre <- as.character(ign_revised$genre)

# Removed games with missing genre 
ign_revised <- ign_revised %>%
	  filter(genre != "")

# Filter for games in certain 5 year period (2012-2016)
year_start <- 2012
year_end <- 2016

ign_revised <- ign_revised %>% 
	  filter(release_year >= year_start & release_year <= year_end)

# Filter games released on multiple platform
multiple_platform <- ign_revised[duplicated(ign_revised$title) | duplicated(ign_revised$title, fromLast=TRUE),]

# Obtain the distinct game platform and order alphabetically
dis_platform <- as.character(unique(ign_revised$platform)) 
dis_platform <- sort(dis_platform)

# Removing duplicate title games in main dataset
ign_revised <- ign_revised[!duplicated(ign_revised$title),]

# Order videogames alphabetically
ign_revised <- ign_revised[order(ign_revised$title),]
multiple_platform <- multiple_platform[order(multiple_platform$title),]

# Add distinct platform list as columns to main dataset
ign_revised[dis_platform] <- as.list(dis_platform)

# Original dataset showing only title and platform
ign_temp <- ign %>% filter(!is.na(genre)) %>% 
	  filter(release_year >= year_start & release_year <= year_end) %>% 
    select(title, platform) 

# Applying 1 (Yes) or 0 (No) to games if they appear in the platform columns
ign_temp$value = 1
ign_temp_wide = reshape2::dcast(title ~ platform, data = ign_temp,
                           value.var = "value", fill = 0)

ign_revised <- merge(ign_revised[1:11], ign_temp_wide, by = "title")

# Remove the old platform column, and unused x1, url columns
ign_revised <- ign_revised %>% 
               select(-platform)  
ign_revised <- ign_revised %>% 
               select(-X1)
ign_revised <- ign_revised %>% 
               select(-url)

# Total Sum of Platform winner of editors award in tidyr form
df_won <- ign_revised %>% filter(editors_choice == "Y") %>% 
  select(Android:`Xbox One`) %>% 
  summarise_each(funs(sum))

df_lost <- ign_revised %>% filter(editors_choice == "N") %>% 
  select(Android:`Xbox One`) %>% 
  summarise_each(funs(sum))

tot_platform <- rbind(df_won, df_lost)
rownames(tot_platform) <- c("Won", "Lost")

tot_platform["award"] <- rownames(tot_platform)
tot_platform <- melt(tot_platform, id.vars="award", 
                value.name="Games", variable.name="Platform")

# Total Sum of Platform winner of editors award in horizontal form
won_sum <- t(df_won)
lost_sum <- t(df_lost)
colnames(won_sum) <- c("Won")
colnames(lost_sum) <- c("Lost")
tot_platform_2 <-  merge(won_sum, lost_sum, by=0, all=TRUE)
colnames(tot_platform_2) <- c("Platform", "Won", "Lost")
tot_platform_2$Platform <- as.character(tot_platform_2$Platform)
tot_platform_2$Won <- as.numeric(tot_platform_2$Won)
tot_platform_2$Lost <- as.numeric(tot_platform_2$Lost)

tot_plat2_tidy <- ddply(melt(tot_platform_2, id.vars = 'Platform'),
                        .(Platform), mutate, prop = value / sum(value))
tot_plat2_tidy$variable <- as.character(tot_plat2_tidy$variable)
tot_plat2_tidy$value <- as.numeric(tot_plat2_tidy$value)
tot_plat2_tidy$prop <- as.numeric(tot_plat2_tidy$prop)

# New column for total number of platforms game appears on
ign_revised$tot_Plat <- rowSums(ign_revised[,c(9:32)])

# New column for word count of the title
ign_revised$word_count <- sapply(ign_revised$title, function(x) length(unlist(strsplit(as.character(x), "\\W+"))))
ign_revised$word_count <- ifelse(grepl("^1$", ign_revised$word_count, ignore.case = T), 1, 
         ifelse(grepl("^2", ign_revised$word_count, ignore.case = T), 2,
         ifelse(grepl("^3", ign_revised$word_count, ignore.case = T), 3,        
         ifelse(grepl("^4", ign_revised$word_count, ignore.case = T), 4,
         ifelse(grepl("^5", ign_revised$word_count, ignore.case = T), 5,
         ifelse(grepl("^6", ign_revised$word_count, ignore.case = T), 6,
         ifelse(grepl("^7", ign_revised$word_count, ignore.case = T), 7,
         ifelse(grepl("^8", ign_revised$word_count, ignore.case = T), 8,
         ifelse(grepl("^9", ign_revised$word_count, ignore.case = T), 9, 10))))))))) # 10+ words classified as 10

# New column for character count of title
ign_revised$char_count <- sapply(ign_revised$title, function(x) nchar(x))

# New column for starting letter/# of title
ign_revised$title_start <- ifelse(grepl("^A", ign_revised$title, ignore.case = T), "A", 
         ifelse(grepl("^B", ign_revised$title, ignore.case = T), "B",
         ifelse(grepl("^C", ign_revised$title, ignore.case = T), "C",        
         ifelse(grepl("^D", ign_revised$title, ignore.case = T), "D",
         ifelse(grepl("^E", ign_revised$title, ignore.case = T), "E",
         ifelse(grepl("^F", ign_revised$title, ignore.case = T), "F",
         ifelse(grepl("^G", ign_revised$title, ignore.case = T), "G",
         ifelse(grepl("^H", ign_revised$title, ignore.case = T), "H",
         ifelse(grepl("^I", ign_revised$title, ignore.case = T), "I",
         ifelse(grepl("^J", ign_revised$title, ignore.case = T), "J",
         ifelse(grepl("^K", ign_revised$title, ignore.case = T), "K",
         ifelse(grepl("^L", ign_revised$title, ignore.case = T), "L",
         ifelse(grepl("^M", ign_revised$title, ignore.case = T), "M",
         ifelse(grepl("^N", ign_revised$title, ignore.case = T), "N",
         ifelse(grepl("^O", ign_revised$title, ignore.case = T), "O",
         ifelse(grepl("^P", ign_revised$title, ignore.case = T), "P",
         ifelse(grepl("^Q", ign_revised$title, ignore.case = T), "Q",
         ifelse(grepl("^R", ign_revised$title, ignore.case = T), "R",
         ifelse(grepl("^S", ign_revised$title, ignore.case = T), "S",
         ifelse(grepl("^T", ign_revised$title, ignore.case = T), "T",
         ifelse(grepl("^U", ign_revised$title, ignore.case = T), "U",
         ifelse(grepl("^V", ign_revised$title, ignore.case = T), "V",
         ifelse(grepl("^W", ign_revised$title, ignore.case = T), "W",
         ifelse(grepl("^X", ign_revised$title, ignore.case = T), "X",
         ifelse(grepl("^Y", ign_revised$title, ignore.case = T), "Y",
         ifelse(grepl("^Z", ign_revised$title, ignore.case = T), "Z","#"))))))))))))))))))))))))))

# New column for games with numbers (sequel) in title
ign_revised$number <- ifelse(grepl(".*([0-9]+)", ign_revised$title, ignore.case = T), "Yes","No")

# New column for games with franchise name in title
ign_revised$franchise <- ifelse(grepl("Mario", ign_revised$title, ignore.case = T), "Mario", 
         ifelse(grepl("Zelda", ign_revised$title, ignore.case = T), "Zelda",
         ifelse(grepl("Pokemon", ign_revised$title, ignore.case = T), "Pokemon",        
         ifelse(grepl("Halo", ign_revised$title, ignore.case = T), "Halo",
         ifelse(grepl("LEGO", ign_revised$title, ignore.case = T), "LEGO",
         ifelse(grepl("Star Wars", ign_revised$title, ignore.case = T), "Star Wars",
         ifelse(grepl("Call of Duty", ign_revised$title, ignore.case = T), "Call of Duty",
         ifelse(grepl("FIFA", ign_revised$title, ignore.case = T), "FIFA",
         ifelse(grepl("^NBA", ign_revised$title, ignore.case = T), "NBA",
         ifelse(grepl("Grand Theft Auto", ign_revised$title, ignore.case = T), "Grand Theft Auto",
         ifelse(grepl("Tom Clancy", ign_revised$title, ignore.case = T), "Tom Clancy",
         ifelse(grepl("Street Fighter", ign_revised$title, ignore.case = T), "Street Fighter",
         ifelse(grepl("Warcraft", ign_revised$title, ignore.case = T), "Warcraft",
         ifelse(grepl("Resident Evil", ign_revised$title, ignore.case = T), "Resident Evil",
         ifelse(grepl("Metal Gear", ign_revised$title, ignore.case = T), "Metal Gear",
         ifelse(grepl("Dark Souls", ign_revised$title, ignore.case = T), "Dark Souls",
         ifelse(grepl("Forza", ign_revised$title, ignore.case = T), "Forza",
         ifelse(grepl("Final Fantasy", ign_revised$title, ignore.case = T), "Final Fantasy",
         ifelse(grepl("Uncharted", ign_revised$title, ignore.case = T), "Uncharted","Other")))))))))))))))))))

# New column for top 10 genre
ign_revised$top_genre <- ifelse(grepl("^Action", ign_revised$genre, ignore.case = T), "Action", 
         ifelse(grepl("^Adventure", ign_revised$genre, ignore.case = T), "Adventure",
         ifelse(grepl("^Fighting", ign_revised$genre, ignore.case = T), "Fighting",        
         ifelse(grepl("^Platformer", ign_revised$genre, ignore.case = T), "Platformer",
         ifelse(grepl("^Racing", ign_revised$genre, ignore.case = T), "Racing",
         ifelse(grepl("^RPG", ign_revised$genre, ignore.case = T), "RPG",
         ifelse(grepl("^Shooter", ign_revised$genre, ignore.case = T), "Shooter",
         ifelse(grepl("^Sports", ign_revised$genre, ignore.case = T), "Sports",
         ifelse(grepl("^Strategy", ign_revised$genre, ignore.case = T), "Strategy","Other")))))))))

################ EDA Plots #################################

# Plotting Ordered Mean Scores of Genre with standard error bars (NEW)
meanScore_Plat_order <- aggregate(ign_revised$score~ign_revised$genre, FUN = mean)
colnames(meanScore_Plat_order) <- c("Genre", "Mean_Score")
meanScore_Plat_order$Genre <- factor(meanScore_Plat_order$Genre, 
                              levels = meanScore_Plat_order$Genre[order(meanScore_Plat_order$Mean_Score)])

# Adding standard error to mean score
SE_meanScores <- aggregate(ign_revised$score~ign_revised$genre,ign_revised, st.err)
colnames(SE_meanScores) <- c("Genre", "SE")
SE_meanScores[is.na(SE_meanScores)] <- 0                                #genre with 1 game se=0
meanScore_Plat_order <- cbind(meanScore_Plat_order, SE_meanScores[,2])
colnames(meanScore_Plat_order) <- c("Genre","Mean_Score","SE")
avg_meanScore_Plat <- mean(meanScore_Plat_order$Mean_Score)

ggplot(meanScore_Plat_order, aes(x = Genre, y = Mean_Score)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=Mean_Score-SE, ymax=Mean_Score+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_meanScore_Plat, linetype="dashed", color = "red") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 10)) +
        labs(title = "Ordered Mean Score of Games of All Genre from 2012-2016", 
             x = "Genre", 
             y = "Mean Score")  

# Box Plotting Mean Score of Year
ggplot(ign_revised, aes(x = release_year, y = score, group = factor(release_year))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 10.5)) +
        labs(title = "Mean Score of Games from 2012-2016", 
             x = "Year", 
             y = "Mean Score")

# Box Plotting Mean Score of Month 
ggplot(ign_revised, aes(x = release_month, y = score, group = factor(release_month))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_x_continuous(expand = c(0, 0), breaks = seq(1,12, by = 1), limits=c(0.5,12.5)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 10.5)) +
        labs(title = "Monthly Mean Score of Games from 2012-2016", 
             x = "Month", 
             y = "Mean Score")

# Box Plotting Mean Score of Games with Numbered Title 
ggplot(ign_revised, aes(x = number, y = score, group = factor(number))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 10.5)) +
        labs(title = "Mean Score of Games With Numbered Game Title from 2012-2016", 
             x = "Number in Game Title", 
             y = "Mean Score")

# Box Plotting Mean Score of Games depending on # of Platforms released on 
ggplot(ign_revised, aes(x = tot_Plat, y = score, group = factor(tot_Plat))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_x_continuous(expand = c(0, 0), breaks = seq(1,8, by = 1), limits=c(0.5,8.5)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 10.5)) +
        labs(title = "Mean Score of Total Number of Platform Releases from 2012-2016", 
             x = "Total Number of Platform Releases", 
             y = "Mean Score")

# Box Plotting Mean Score of Games depending on word count of title
ggplot(ign_revised, aes(x = word_count, y = score, group = factor(word_count))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_x_continuous(expand = c(0, 0), breaks = seq(1,10, by = 1), limits=c(0.5,10.5)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 10.5)) +
        labs(title = "Mean Score of Word Count of Titles from 2012-2016", 
             x = "Title's Word Count", 
             y = "Mean Score")

# Plotting Proportion of Editor's Choice award won per Genre w/ Error Bar
prop_Genre_EC <- ign_revised %>%
                      group_by(genre, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_Genre_EC$SE <- sqrt(prop_Genre_EC$freq*(1-prop_Genre_EC$freq)/sum(prop_Genre_EC$n)) #SE of prop
prop_Genre_EC_won <- prop_Genre_EC %>% 
                        filter(editors_choice == 'Y')
avg_Genre_EC_won <- mean(prop_Genre_EC_won$freq)
ggplot(prop_Genre_EC_won, aes(x = genre, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_Genre_EC_won, linetype="dashed", color = "red") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
        labs(title = "Proportion of Editor's Choice Award by Genre in 2012-2016", 
             x = "Genre", 
             y = "Proportion of Winners")

# Plotting Proportion of Editor's Choice award won per Top Genre w/ Error Bar (New)
prop_Top_Genre_EC <- ign_revised %>%
                      group_by(top_genre, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_Top_Genre_EC$SE <- sqrt(prop_Top_Genre_EC$freq*(1-prop_Top_Genre_EC$freq)/sum(prop_Top_Genre_EC$n)) #SE of prop
prop_Top_Genre_EC_won <- prop_Top_Genre_EC %>% 
                        filter(editors_choice == 'Y')
avg_Top_Genre_EC_won <- mean(prop_Top_Genre_EC_won$freq)
ggplot(prop_Top_Genre_EC_won, aes(x = top_genre, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_Top_Genre_EC_won, linetype="dashed", color = "red") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
        labs(title = "Proportion of Editor's Choice Award by Top Genres in 2012-2016", 
             x = "Top Genres", 
             y = "Proportion of Winners")

# Plotting Proportion of Editor's Choice award won per Total Number of Platform Releases w/ Error Bar (NEW) 
prop_TP_EC <- ign_revised %>%
                      group_by(tot_Plat, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_TP_EC$SE <- sqrt(prop_TP_EC$freq*(1-prop_TP_EC$freq)/sum(prop_TP_EC$n)) #SE of prop
prop_TP_EC_won <- prop_TP_EC %>% 
                        filter(editors_choice == 'Y')
avg_TP_EC_won <- mean(prop_TP_EC_won$freq)
ggplot(prop_TP_EC_won, aes(x = tot_Plat, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_TP_EC_won, linetype="dashed", color = "red") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_x_continuous(expand = c(0, 0), breaks = seq(1,7, by = 1), limits=c(0.5,7.5)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
        labs(title = "Proportion of Editor's Choice Award by Total Number of Platform Releases in 2012-2016", 
             x = "Total Number of Platform Releases", 
             y = "Proportion of Winners")

# Plotting Proportion of Editor's Choice award won per Word Count of Title w/ Error Bar (NEW) 
prop_word_EC <- ign_revised %>%
                      group_by(word_count, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_word_EC$SE <- sqrt(prop_word_EC$freq*(1-prop_word_EC$freq)/sum(prop_word_EC$n)) #SE of prop
prop_word_EC_won <- prop_word_EC %>% 
                        filter(editors_choice == 'Y')
avg_word_EC_won <- mean(prop_word_EC_won$freq)
ggplot(prop_word_EC_won, aes(x = word_count, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_word_EC_won, linetype="dashed", color = "red") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_x_continuous(expand = c(0, 0), breaks = seq(1,10, by = 1), limits=c(0.5,10.5)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
        labs(title = "Proportion of Editor's Choice Award by Word Count of Title in 2012-2016", 
             x = "Word Count of Title", 
             y = "Proportion of Winners")

# Plotting Proportion of Editor's Choice award won per Year w/ Error Bar 
prop_Year_EC <- ign_revised %>%
                      group_by(release_year, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_Year_EC$SE <- sqrt(prop_Year_EC$freq*(1-prop_Year_EC$freq)/sum(prop_Year_EC$n)) #SE of prop
prop_Year_EC_won <- prop_Year_EC %>% 
                        filter(editors_choice == 'Y')
ggplot(prop_Year_EC_won, aes(x = release_year, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.2, colour="black") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
        labs(title = "Proportion of Editor's Choice Award in 2012-2016", 
             x = "Year", 
             y = "Proportion of Winners")

# Plotting Proportion of Editor's Choice award won per Month w/ Error Bar 
prop_Month_EC <- ign_revised %>%
                      group_by(release_month, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_Month_EC$SE <- sqrt(prop_Month_EC$freq*(1-prop_Month_EC$freq)/sum(prop_Month_EC$n)) #SE of prop
prop_Month_EC_won <- prop_Month_EC %>% 
                        filter(editors_choice == 'Y')
avg_Month_EC_won <- mean(prop_Month_EC_won$freq)
ggplot(prop_Month_EC_won, aes(x = release_month, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_Month_EC_won, linetype="dashed", color = "red") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_x_continuous(expand = c(0, 0), breaks = seq(1,12, by = 1), limits=c(0.5,12.5)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
        labs(title = "Monthly Proportion of Editor's Choice Award in 2012-2016", 
             x = "Month", 
             y = "Proportion of Winners")

# Plotting Proportion of Editor's Choice award won per Numbered Game Title w/ Error Bar (NEW) 
prop_Number_EC <- ign_revised %>%
                      group_by(number, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_Number_EC$SE <- sqrt(prop_Number_EC$freq*(1-prop_Number_EC$freq)/sum(prop_Number_EC$n)) #SE of prop
prop_Number_EC_won <- prop_Number_EC %>% 
                        filter(editors_choice == 'Y')
ggplot(prop_Number_EC_won, aes(x = number, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.1, colour="black") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
        labs(title = "Proportion of Editor's Choice Award by Numbered Game Titles in 2012-2016", 
             x = "Number in Game Title", 
             y = "Proportion of Winners")

# Prelim chi-squared between containing number and winning editor's choice
chisq.test(table(ign_revised$number, ign_revised$editors_choice))

# As the p-value 0.00623 is less than the .05 significance level, we  
# reject the null hypothesis that a video game containing a number is independent of the 
# that game winning an editor's choice award. (X-squared = 7.4826, df = 1)

# Plotting Proportion of Editor's Choice award won per Franchise w/ Error Bar (NEW)
prop_Fran_EC <- ign_revised %>%
                      group_by(franchise, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_Fran_EC$SE <- sqrt(prop_Fran_EC$freq*(1-prop_Fran_EC$freq)/sum(prop_Fran_EC$n)) #SE of prop
prop_Fran_EC_won <- prop_Fran_EC %>% 
                        filter(editors_choice == 'Y')
avg_Fran_EC_won <- mean(prop_Fran_EC_won$freq)
ggplot(prop_Fran_EC_won, aes(x = franchise, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_Fran_EC_won, linetype="dashed", color = "red") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
        labs(title = "Proportion of Editor's Choice Award by Franchise in 2012-2016", 
             x = "Franchise", 
             y = "Proportion of Winners")

# Plotting Proportion of Editor's Choice award won per Starting Letter (SL) of title w/ Error Bar (NEW) 
prop_SL_EC <- ign_revised %>%
                      group_by(title_start, editors_choice) %>%
                      summarise (n = n()) %>%
                      mutate(freq = n / sum(n))
prop_SL_EC$SE <- sqrt(prop_SL_EC$freq*(1-prop_SL_EC$freq)/sum(prop_SL_EC$n)) #SE of prop
prop_SL_EC_won <- prop_SL_EC %>% 
                        filter(editors_choice == 'Y')
avg_SL_EC_won <- mean(prop_SL_EC_won$freq)
ggplot(prop_SL_EC_won, aes(x = title_start, y = freq)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=freq-SE, ymax=freq+SE), width=0.1, colour="black") +
  geom_hline(yintercept = avg_SL_EC_won, linetype="dashed", color = "red") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
        labs(title = "Proportion of Editor's Choice Award by Starting Letter of Game Title in 2012-2016", 
             x = "Starting Letter of Game Title", 
             y = "Proportion of Winners")

# Prelim chi-squared between starting letter and winning editor's choice
chisq.test(table(ign_revised$title_start, ign_revised$editors_choice))

# As the p-value 0.0007802 is less than the .05 significance level, we  
# reject the null hypothesis that the starting letter of a video game is independent of the 
# that game winning an editor's choice award. (X-squared = 54.903, df = 26)
        
# Plotting Proportion of Editor's Choice award won per Platform w/ Error Bar (NEW)
prop_Platform_EC <- tot_plat2_tidy 
prop_Platform_EC$SE <- sqrt(prop_Platform_EC$prop*(1-prop_Platform_EC$prop)/sum(prop_Platform_EC$value)) #SE of prop
prop_Platform_EC_won <- prop_Platform_EC %>% 
                        filter(variable == 'Won')
avg_Platform_EC_won <- mean(prop_Platform_EC_won$prop)
ggplot(prop_Platform_EC_won, aes(x = Platform, y = prop)) + 
  geom_point(col = "Blue") +
  geom_errorbar(aes(ymin=prop-SE, ymax=prop+SE), width=0.2, colour="black") +
  geom_hline(yintercept = avg_Platform_EC_won, linetype="dashed", color = "red") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +
        labs(title = "Proportion of Editor's Choice Award by Platform in 2012-2016", 
             x = "Platform", 
             y = "Proportion of Winners")

# Box Plotting Score of Games Winning Editor's Choice Award 
ggplot(ign_revised, aes(x = editors_choice, y = score, group = factor(editors_choice))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), breaks = seq(0,10,by = 1), limits = c(0, 11)) +
        labs(title = "Score of Games Winning Editor's Choice Award from 2012-2016", 
             x = "Editor's Choice Award", 
             y = "Score")

# Box Plotting Word Count of Title of Games Winning Editor's Choice Award (NEW)
ggplot(ign_revised, aes(x = editors_choice, y = word_count, group = factor(editors_choice))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), breaks = seq(0,10,by = 1), limits = c(0, 10.5)) +
        labs(title = "Word Count of Game Title Winning Editor's Choice Award from 2012-2016", 
             x = "Editor's Choice Award", 
             y = "Word Count")

# Box Plotting Total Number of Platform Releases for Games Winning Editor's Choice Award (NEW)
ggplot(ign_revised, aes(x = editors_choice, y = tot_Plat, group = factor(editors_choice))) + 
  geom_boxplot() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5),
        plot.title = element_text(hjust = 0.5, line = 4, face="bold")) +
        scale_y_continuous(expand = c(0, 0), breaks = seq(0,10,by = 1), limits = c(0, 11)) +
        labs(title = "Total Number of Platform Releases for Games Winning Editor's Choice Award from 2012-2016", 
             x = "Editor's Choice Award", 
             y = "Total Number of Platform Releases")

############# Logistic Regression ###############################

# Creating model training and testing set
# Make Y=1, N = 0 for LR to work
ign_revised_2 <- ign_revised
ign_revised_2$editors_choice <- ifelse(grepl("Y", ign_revised_2$editors_choice, ignore.case = T), 1,0)

set.seed(500)
split = sample.split(ign_revised_2$editors_choice, SplitRatio = 0.75)
EC_Train = subset(ign_revised_2, split == TRUE)
EC_Test = subset(ign_revised_2, split == FALSE)

# Logistic Regression of Editor's Choice
# All Variables 
# EC_LR = glm(editors_choice ~ genre + release_year + release_month + release_day + Android + iPad + iPhone + Linux + Macintosh + `New Nintendo 3DS` + `Nintendo 3DS` + `Nintendo DS` + `Nintendo DSi` + Ouya + PC + `PlayStation 3` +`PlayStation 4` + `PlayStation Portable` + `PlayStation Vita` + `SteamOS` + `Web Games` + Wii + `Wii U` + `Windows Phone` + `Windows Surface` + `Xbox 360` + `Xbox One` + tot_Plat + word_count + char_count + title_start + number + franchise + top_genre, data= EC_Train, family = binomial)

# # Testing linear regression models
# EC_LR = glm(editors_choice ~ iPhone + `Nintendo 3DS` + `Nintendo 3DS` + PC +`PlayStation 4` + `PlayStation Vita` + `Xbox 360` + top_genre, data= EC_Train, family = binomial)
# 
# EC_LR = glm(editors_choice ~ iPhone + `Nintendo 3DS` + `Nintendo 3DS` + PC +`PlayStation 4` + `PlayStation Vita` + `Xbox 360` + franchise + title_start + genre, data= EC_Train, family = binomial)
# 
# EC_LR = glm(editors_choice ~ iPhone + `Nintendo 3DS` + `Nintendo 3DS` + PC +`PlayStation 4` + `PlayStation Vita` + tot_Plat + top_genre + number + word_count, data= EC_Train, family = binomial)
# 
# EC_LR = glm(editors_choice ~ iPhone + PC +`PlayStation 4` + release_month + franchise + title_start + tot_Plat + word_count, data= EC_Train, family = binomial)

# Final Variables
EC_LR = glm(editors_choice ~ release_month + iPad + iPhone + Linux + Macintosh + `New Nintendo 3DS` + `Nintendo 3DS` + `Nintendo DS` + `Nintendo DSi` + PC + `PlayStation 3` +`PlayStation 4` + `PlayStation Portable` + `PlayStation Vita`+ `Web Games` + Wii + `Wii U` + `Windows Phone` + `Windows Surface` + `Xbox 360` + `Xbox One` + tot_Plat + word_count + char_count + number + franchise + top_genre, data= EC_Train, family = binomial)
summary(EC_LR)

# Probability Summary of True Outcome
predictTrain = predict(EC_LR, type = "response")
summary(predictTrain)
tapply(predictTrain, EC_Train$editors_choice, mean)

# Higher probability of predicting winner than loser of EC
#         0         1 
# 0.1550116 0.2933609 

# Confusion Matrix of Editior's Choice
CM_EC <- table(EC_Train$editors_choice, predictTrain > 0.5)

# Sensitivity of CM/True Positive Rate: TP/(TP + FN)
sensitivity = (CM_EC[2,2])/(CM_EC[2,2] + CM_EC[2,1])
# Specificity of CM/True Negative Rate: TN/(TN + FP)
specificity = (CM_EC[1,1])/(CM_EC[1,1] + CM_EC[1,2]) 
# Accuracy: (TN + TP)/N -> Max: .8275
accuracy = (CM_EC[1,1] + CM_EC[2,2])/(CM_EC[1,1] + CM_EC[1,2] + CM_EC[2,1] + CM_EC[2,2]) 
# Error Rate: (FP + FN)/N -> Min: .1724
error_rate = (CM_EC[1,2] + CM_EC[2,1])/(CM_EC[1,1] + CM_EC[1,2] + CM_EC[2,1] + CM_EC[2,2])  

# ROC curve
ROCRpred = prediction(predictTrain, EC_Train$editors_choice)
ROCRpref = performance(ROCRpred, "tpr", "fpr") #true positive and false pos rate
plot(ROCRpref, colorize = TRUE, print.cutoffs.at = seq(0,1,0.1), text.adj = c(-0.2,1.7)) 

# AUC: positive and negative proportion of prediction
as.numeric(performance(ROCRpred, "auc")@y.values)   

```

